name: NuGet

on:
  push:
    branches:
      - master

jobs:
  build-from-push:
    name: Requested by Push
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - run: echo
 
  build:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/Bannerlord-Unofficial-Tools-Resources/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build Solution (Release)
      run: dotnet build --configuration Release
      
    - name: Pack MCM (Release)
      run: dotnet pack MCM.NuGet/MCM.NuGet.csproj --configuration Release -o "./packages" 
      
    - name: Pack MCM.Integrated (Release)
      run: dotnet pack MCM.Integrated.NuGet/MCM.Integrated.NuGet.csproj --configuration Release -o "./packages"
      
    - name: Push with dotnet
      run: dotnet nuget push "./packages/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
