# Will only be triggered on the master branch by any workflow that uses repository dispatch
name: NuGet Publish

on:
  repository_dispatch:
    types:
      - publish-on-nuget

jobs:
  publish-on-nuget:
    name: NuGet publish requested by ${{github.workflow}} workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.300
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build Solution (Release)
      run: dotnet build --configuration Release

    - name: Pack MCM (Release)
      run: dotnet pack MCM.NuGet/MCM.NuGet.csproj --configuration Release -o "./packages" 

    - name: Pack MCM.Integrated (Release)
      run: dotnet pack MCM.Integrated.NuGet/MCM.Integrated.NuGet.csproj --configuration Release -o "./packages"

    - name: Push with dotnet
      run: dotnet nuget push "./packages/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
